//
// https://en.cppreference.com/w/cpp/iterator/distance#Example
//
#include <algorithm>
#include <cmath>
#include <complex>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <random>
#include <valarray>
#include <vector>

namespace iterator_distance_test {
void run() {
  std::vector<int> v{3, 1, 4};
  std::cout << "distance(first, last) = "
            << std::distance(v.begin(), v.end()) << '\n'
            << "distance(last, first) = "
            << std::distance(v.end(), v.begin()) << '\n';

  static constexpr auto il = {3, 1, 4};
  // Since C++17 distance can be used in constexpr context.
  static_assert(std::distance(il.begin(), il.end()) == 3);
  static_assert(std::distance(il.end(), il.begin()) == -3);
}
} // namespace iterator_distance_test

//
// https://en.cppreference.com/w/cpp/iterator/advance#Example
//
namespace iterator_advance_test {
void run() {
  std::vector<int> v{3, 1, 4};

  auto vi = v.begin();
  std::advance(vi, 2);
  std::cout << *vi << ' ';

  vi = v.end();
  std::advance(vi, -2);
  std::cout << *vi << '\n';
}
} // namespace iterator_advance_test

//
// https://en.cppreference.com/w/cpp/iterator/next#Example
//
namespace iterator_next_test {
void run() {
  std::vector<int> v{4, 5, 6};

  auto it = v.begin();
  auto nx = std::next(it, 2);
  std::cout << *it << ' ' << *nx << '\n';

  it = v.end();
  nx = std::next(it, -2);
  std::cout << ' ' << *nx << '\n';
}
} // namespace iterator_next_test

//
// https://en.cppreference.com/w/cpp/iterator/back_inserter#Example
//
namespace back_inserter_test {
void run() {
  std::vector<int> v{1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
  std::fill_n(std::back_inserter(v), 3, -1);
  for (int n : v) {
    std::cout << n << ' ';
  }
  std::cout << '\n';
}
} // namespace back_inserter_test

//
// https://en.cppreference.com/w/cpp/numeric/complex#Example
//
namespace complex_test {
void run() {
  using namespace std::complex_literals;
  std::cout << std::fixed << std::setprecision(1);

  std::complex<double> z1 = 1i * 1i; // imaginary unit squared
  std::cout << "i * i = " << z1 << '\n';

  std::complex<double> z2 = 1.0 + 2i, z3 = 1.0 - 2i; // conjugates
  std::cout << "(1+2i)*(1-2i) = " << z2 * z3 << '\n';
}
} // namespace complex_test

//
// https://en.cppreference.com/w/cpp/numeric/valarray/slice#Example
//
namespace valarray_slice_test {
class Matrix {
  std::valarray<int> data;
  int dim;

public:
  Matrix(int r, int c) : data(r * c), dim(c) {}
  int &operator()(int r, int c) { return data[r * dim + c]; }
  int trace() const { return data[std::slice(0, dim, dim + 1)].sum(); }
};

void run() {
  Matrix m(3, 3);
  int n = 0;
  for (int r = 0; r < 3; ++r) {
    for (int c = 0; c < 3; ++c) {
      m(r, c) = ++n;
    }
  }
  std::cout << "Trace of the matrix (1,2,3) (4,5,6) (7,8,9) is "
            << m.trace() << '\n';
}
} // namespace valarray_slice_test

//
// https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution#Example
//
namespace uniform_int_distribution_test {
void run() {
  // The cppreference example uses std::random_device to seed the engine.
  // Kernel tests use a fixed seed to avoid depending on hosted entropy APIs.
  std::mt19937 gen{};
  std::uniform_int_distribution<> distrib(1, 6);

  // Use distrib to transform the random unsigned int generated by gen into an
  // int in [1, 6].
  for (int n = 0; n != 10; ++n) {
    std::cout << distrib(gen) << ' ';
  }
  std::cout << '\n';
}
} // namespace uniform_int_distribution_test
